# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_CLK_SHIKRA_DEBUGCC) += debugcc-shikra.o

obj-$(CONFIG_CLK_SHIKRA_DISPCC) += dispcc-shikra.o

obj-$(CONFIG_CLK_SHIKRA_GCC) += gcc-shikra.o

obj-$(CONFIG_CLK_SHIKRA_GPUCC) += gpucc-shikra.o

obj-$(CONFIG_CLK_X1E80100_CAMCC) += camcc-x1e80100.o

obj-$(CONFIG_CLK_X1E80100_DISPCC) += dispcc-x1e80100.o

obj-$(CONFIG_CLK_X1E80100_GCC) += gcc-x1e80100.o

obj-$(CONFIG_CLK_X1E80100_GPUCC) += gpucc-x1e80100.o

obj-$(CONFIG_CLK_X1E80100_TCSRCC) += tcsrcc-x1e80100.o

obj-$(CONFIG_CLK_X1P42100_GPUCC) += gpucc-x1p42100.o

obj-$(CONFIG_COMMON_CLK_QCOM) += clk-dummy.o

obj-$(CONFIG_COMMON_CLK_QCOM) += clk-qcom.o
clk-qcom-objs += clk-alpha-pll.o clk-branch.o clk-debug.o clk-hfpll.o clk-opp.o clk-pll.o clk-pm.o clk-rcg.o clk-rcg2.o clk-regmap-divider.o clk-regmap-mux-div.o clk-regmap-mux.o clk-regmap-phy-mux.o clk-regmap.o common.o reset.o vdd-class.o
clk-qcom-$(CONFIG_KRAIT_CLOCKS) += clk-krait.o
clk-qcom-$(CONFIG_QCOM_GDSC) += gdsc.o gdsc-debug.o

obj-$(CONFIG_QCM_DEBUGCC_2290) += debugcc-qcm2290.o

obj-$(CONFIG_QCM_DISPCC_2290) += dispcc-qcm2290.o

obj-$(CONFIG_QCM_GCC_2290) += gcc-qcm2290.o

obj-$(CONFIG_QCM_GPUCC_2290) += gpucc-qcm2290.o

obj-$(CONFIG_QCOM_CLK_RPMH) += clk-rpmh.o

obj-$(CONFIG_QCOM_CLK_SMD_RPM) += clk-smd-rpm.o

obj-$(CONFIG_QCOM_GDSC_REGULATOR) += gdsc-regulator.o

obj-$(CONFIG_SC_AV1ECC_X1P42100) += av1ecc-x1p42100.o

obj-$(CONFIG_SC_CAMCC_7280) += camcc-sc7280.o

obj-$(CONFIG_SC_CAMCC_X1P42100) += camcc-x1p42100.o

obj-$(CONFIG_SC_DEBUGCC_7280) += debugcc-sc7280.o

obj-$(CONFIG_SC_DEBUGCC_X1E80100) += debugcc-x1e80100.o

obj-$(CONFIG_SC_DISPCC_7280) += dispcc-sc7280.o

obj-$(CONFIG_SC_GCC_7280) += gcc-sc7280.o

obj-$(CONFIG_SC_GCC_X1P42100) += gcc-x1p42100.o

obj-$(CONFIG_SC_GPUCC_7280) += gpucc-sc7280.o

obj-$(CONFIG_SC_VIDEOCC_7280) += videocc-sc7280.o

obj-$(CONFIG_SC_VIDEOCC_X1P42100) += videocc-x1p42100.o

obj-$(CONFIG_SDW_DEBUGCC_MONACO) += debugcc-monaco.o

obj-$(CONFIG_SDW_DEBUGCC_VIENNA) += debugcc-vienna.o

obj-$(CONFIG_SDW_DISPCC_MONACO) += dispcc-monaco.o

obj-$(CONFIG_SDW_GCC_MONACO) += gcc-monaco.o

obj-$(CONFIG_SDW_GCC_VIENNA) += gcc-vienna.o

obj-$(CONFIG_SDW_GPUCC_MONACO) += gpucc-monaco.o

obj-$(CONFIG_SDW_GPUCC_VIENNA) += gpucc-vienna.o

obj-$(CONFIG_SM_CAMBISTMCLKCC_CANOE) += cambistmclkcc-canoe.o

obj-$(CONFIG_SM_CAMBISTMCLKCC_SUN) += cambistmclkcc-sun.o

obj-$(CONFIG_SM_CAMCC_4450) += camcc-sm4450.o

obj-$(CONFIG_SM_CAMCC_8350) += camcc-sm8350.o

obj-$(CONFIG_SM_CAMCC_ALOR) += camcc-alor.o

obj-$(CONFIG_SM_CAMCC_CANOE) += camcc-canoe.o

obj-$(CONFIG_SM_CAMCC_CHORA) += camcc-chora.o

obj-$(CONFIG_SM_CAMCC_DIWALI) += camcc-diwali.o

obj-$(CONFIG_SM_CAMCC_SUN) += camcc-sun.o

obj-$(CONFIG_SM_DEBUGCC_4450) += debugcc-sm4450.o

obj-$(CONFIG_SM_DEBUGCC_6115) += debugcc-sm6115.o

obj-$(CONFIG_SM_DEBUGCC_8350) += debugcc-sm8350.o

obj-$(CONFIG_SM_DEBUGCC_ALOR) += debugcc-alor.o

obj-$(CONFIG_SM_DEBUGCC_CANOE) += debugcc-canoe.o

obj-$(CONFIG_SM_DEBUGCC_CHORA) += debugcc-chora.o

obj-$(CONFIG_SM_DEBUGCC_DIWALI) += debugcc-diwali.o

obj-$(CONFIG_SM_DEBUGCC_KHAJE) += debugcc-khaje.o

obj-$(CONFIG_SM_DEBUGCC_MALABAR) += debugcc-malabar.o

obj-$(CONFIG_SM_DEBUGCC_SUN) += debugcc-sun.o

obj-$(CONFIG_SM_DISPCC_4450) += dispcc-sm4450.o

obj-$(CONFIG_SM_DISPCC_6115) += dispcc-sm6115.o

obj-$(CONFIG_SM_DISPCC_8350) += dispcc-sm8350.o

obj-$(CONFIG_SM_DISPCC_CANOE) += dispcc-canoe.o

obj-$(CONFIG_SM_DISPCC_CHORA) += dispcc-chora.o

obj-$(CONFIG_SM_DISPCC_DIWALI) += dispcc-diwali.o

obj-$(CONFIG_SM_DISPCC_KHAJE) += dispcc-khaje.o

obj-$(CONFIG_SM_DISPCC_MALABAR) += dispcc-malabar.o

obj-$(CONFIG_SM_DISPCC_SUN) += dispcc-sun.o

obj-$(CONFIG_SM_EVACC_CANOE) += evacc-canoe.o

obj-$(CONFIG_SM_EVACC_SUN) += evacc-sun.o

obj-$(CONFIG_SM_GCC_4450) += gcc-sm4450.o

obj-$(CONFIG_SM_GCC_6115) += gcc-sm6115.o

obj-$(CONFIG_SM_GCC_8350) += gcc-sm8350.o

obj-$(CONFIG_SM_GCC_ALOR) += gcc-alor.o

obj-$(CONFIG_SM_GCC_CANOE) += gcc-canoe.o

obj-$(CONFIG_SM_GCC_CHORA) += gcc-chora.o

obj-$(CONFIG_SM_GCC_FILLMORE) += gcc-fillmore.o

obj-$(CONFIG_SM_GCC_KHAJE) += gcc-khaje.o

obj-$(CONFIG_SM_GCC_MALABAR) += gcc-malabar.o

obj-$(CONFIG_SM_GCC_SUN) += gcc-sun.o

obj-$(CONFIG_SM_GPUCC_4450) += gpucc-sm4450.o

obj-$(CONFIG_SM_GPUCC_6115) += gpucc-sm6115.o

obj-$(CONFIG_SM_GPUCC_8350) += gpucc-sm8350.o

obj-$(CONFIG_SM_GPUCC_CANOE) += gpucc-canoe.o

obj-$(CONFIG_SM_GPUCC_CHORA) += gpucc-chora.o

obj-$(CONFIG_SM_GPUCC_DIWALI) += gpucc-diwali.o

obj-$(CONFIG_SM_GPUCC_KHAJE) += gpucc-khaje.o

obj-$(CONFIG_SM_GPUCC_MALABAR) += gpucc-malabar.o

obj-$(CONFIG_SM_GPUCC_SUN) += gpucc-sun.o

obj-$(CONFIG_SM_LPASS_AUDIOCC_6115) += lpassaoncc-sm6115.o

obj-$(CONFIG_SM_LPASS_AUDIOCC_6115) += lpassaudiocc-sm6115.o

obj-$(CONFIG_SM_LPASS_AUDIOCC_KHAJE) += lpassaoncc-khaje.o

obj-$(CONFIG_SM_LPASS_AUDIOCC_KHAJE) += lpassaudiocc-khaje.o

obj-$(CONFIG_SM_TCSRCC_CANOE) += tcsrcc-canoe.o

obj-$(CONFIG_SM_TCSRCC_CHORA) += tcsrcc-chora.o

obj-$(CONFIG_SM_TCSRCC_SUN) += tcsrcc-sun.o

obj-$(CONFIG_SM_VIDEOCC_8350) += videocc-sm8350.o

obj-$(CONFIG_SM_VIDEOCC_8550) += videocc-sm8550.o

obj-$(CONFIG_SM_VIDEOCC_CANOE) += videocc-canoe.o

obj-$(CONFIG_SM_VIDEOCC_CHORA) += videocc-chora.o

obj-$(CONFIG_SM_VIDEOCC_DIWALI) += videocc-diwali.o

obj-$(CONFIG_SM_VIDEOCC_SUN) += videocc-sun.o

obj-$(CONFIG_SPMI_PMIC_CLKDIV) += clk-spmi-pmic-div.o

obj-$(CONFIG_SXR_CAMCC_PIKACHU) += camcc-pikachu.o

obj-$(CONFIG_SXR_CAMCC_SERAPH) += camcc-seraph.o

obj-$(CONFIG_SXR_DEBUGCC_PIKACHU) += debugcc-pikachu.o

obj-$(CONFIG_SXR_DEBUGCC_SERAPH) += debugcc-seraph.o

obj-$(CONFIG_SXR_EVACC_PIKACHU) += evacc-pikachu.o

obj-$(CONFIG_SXR_EVACC_SERAPH) += evacc-seraph.o

obj-$(CONFIG_SXR_GCC_PIKACHU) += gcc-pikachu.o

obj-$(CONFIG_SXR_GCC_SERAPH) += gcc-seraph.o

obj-$(CONFIG_SXR_GPUCC_PIKACHU) += gpucc-pikachu.o

obj-$(CONFIG_SXR_GPUCC_SERAPH) += gpucc-seraph.o

obj-$(CONFIG_SXR_LSRCC_SERAPH) += lsrcc-seraph.o

obj-$(CONFIG_SXR_TCSRCC_PIKACHU) += tcsrcc-pikachu.o

obj-$(CONFIG_SXR_TCSRCC_SERAPH) += tcsrcc-seraph.o

obj-$(CONFIG_SXR_VIDEOCC_PIKACHU) += videocc-pikachu.o

obj-$(CONFIG_SXR_VIDEOCC_SERAPH) += videocc-seraph.o

obj-$(CONFIG_VIRTIO_CLK) += virtio_clk.o

obj-$(CONFIG_VIRTIO_CLK) += virtio_clk_direwolf.o

obj-$(CONFIG_VIRTIO_CLK) += virtio_clk_lemans.o

obj-$(CONFIG_VIRTIO_CLK) += virtio_clk_monaco.o
