# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_INTERCONNECT_QCOM_BCM_VOTER) += icc-bcm-voter.o
icc-bcm-voter-objs += bcm-voter.o

obj-$(CONFIG_INTERCONNECT_QCOM_DEBUG) += icc-debug.o

obj-$(CONFIG_INTERCONNECT_QCOM_RPMH) += icc-rpmh.o

obj-$(CONFIG_INTERCONNECT_QCOM_RPM) += icc-rpm.o

obj-$(CONFIG_INTERCONNECT_QCOM_SHIKRA) += qnoc-shikra.o
qnoc-shikra-objs += shikra.o

obj-$(CONFIG_INTERCONNECT_QCOM_CANOE) += qnoc-canoe.o
qnoc-canoe-objs += canoe.o

obj-$(CONFIG_INTERCONNECT_QCOM_CHORA) += qnoc-chora.o
qnoc-chora-objs += chora.o

obj-$(CONFIG_INTERCONNECT_QCOM_X1P42100) += qnoc-x1p42100.o
qnoc-x1p42100-objs += x1p42100.o

obj-$(CONFIG_INTERCONNECT_QCOM_X1E80100) += qnoc-x1e80100.o
qnoc-x1e80100-objs += x1e80100.o

obj-$(CONFIG_INTERCONNECT_QCOM_MALABAR) += qnoc-malabar.o
qnoc-malabar-objs += malabar.o

obj-$(CONFIG_INTERCONNECT_QCOM_LAHAINA) += qnoc-lahaina.o
qnoc-lahaina-objs += lahaina.o

obj-$(CONFIG_INTERCONNECT_QCOM_RAVELIN) += qnoc-ravelin.o
qnoc-ravelin-objs += ravelin.o

obj-$(CONFIG_INTERCONNECT_QCOM_YUPIK) += qnoc-yupik.o
qnoc-yupik-objs += yupik.o

obj-$(CONFIG_INTERCONNECT_QCOM_QOS) += qnoc-qos.o

obj-$(CONFIG_INTERCONNECT_QCOM_QOS_RPM) += qnoc-qos-rpm.o

obj-$(CONFIG_INTERCONNECT_QCOM_BENGAL) += qnoc-bengal.o
qnoc-bengal-objs += bengal.o

obj-$(CONFIG_INTERCONNECT_QCOM_SCUBA) += qnoc-scuba.o
qnoc-scuba-objs += scuba.o

obj-$(CONFIG_INTERCONNECT_QCOM_MONACO) += qnoc-monaco.o
qnoc-monaco-objs += monaco.o

obj-$(CONFIG_INTERCONNECT_QCOM_SUN) += qnoc-sun.o
qnoc-sun-objs += sun.o

obj-$(CONFIG_INTERCONNECT_QCOM_VIENNA) += qnoc-vienna.o
qnoc-vienna-objs += vienna.o

obj-$(CONFIG_INTERCONNECT_QCOM_ALOR) += qnoc-alor.o
qnoc-alor-objs += alor.o

obj-$(CONFIG_INTERCONNECT_QCOM_SERAPH) += qnoc-seraph.o
qnoc-seraph-objs += seraph.o

obj-$(CONFIG_INTERCONNECT_QCOM_PIKACHU) += qnoc-pikachu.o
qnoc-pikachu-objs += pikachu.o

obj-$(CONFIG_INTERCONNECT_QCOM_DIWALI) += qnoc-diwali.o
qnoc-diwali-objs := diwali.o
